// Copyright 2015-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/aws/amazon-ecs-cli/ecs-cli/modules/clients/aws/cloudwatchevents (interfaces: CloudWatchEventsClient)

package mock_cloudwatchevents

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of CloudWatchEventsClient interface
type MockCloudWatchEventsClient struct {
	ctrl     *gomock.Controller
	recorder *_MockCloudWatchEventsClientRecorder
}

// Recorder for MockCloudWatchEventsClient (not exported)
type _MockCloudWatchEventsClientRecorder struct {
	mock *MockCloudWatchEventsClient
}

func NewMockCloudWatchEventsClient(ctrl *gomock.Controller) *MockCloudWatchEventsClient {
	mock := &MockCloudWatchEventsClient{ctrl: ctrl}
	mock.recorder = &_MockCloudWatchEventsClientRecorder{mock}
	return mock
}

func (_m *MockCloudWatchEventsClient) EXPECT() *_MockCloudWatchEventsClientRecorder {
	return _m.recorder
}
