// Copyright 2015-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/aws/amazon-ecs-cli/ecs-cli/modules/clients/aws/iam (interfaces: IAMClient)

package mock_iam

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of IAMClient interface
type MockIAMClient struct {
	ctrl     *gomock.Controller
	recorder *_MockIAMClientRecorder
}

// Recorder for MockIAMClient (not exported)
type _MockIAMClientRecorder struct {
	mock *MockIAMClient
}

func NewMockIAMClient(ctrl *gomock.Controller) *MockIAMClient {
	mock := &MockIAMClient{ctrl: ctrl}
	mock.recorder = &_MockIAMClientRecorder{mock}
	return mock
}

func (_m *MockIAMClient) EXPECT() *_MockIAMClientRecorder {
	return _m.recorder
}
